services:
  - type: web
    name: freefaceed-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python database.py
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
    pythonVersion: 3.10